# Generated by Django 5.1.4 on 2025-01-09 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True,
                        help_text="Напиши место",
                        max_length=150,
                        null=True,
                        verbose_name="Место для выполнения привычки",
                    ),
                ),
                (
                    "time_for_habit",
                    models.TimeField(
                        blank=True,
                        help_text="Время для выполнения привычки",
                        null=True,
                        verbose_name="Время",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        blank=True,
                        help_text="Напиши что делаешь",
                        max_length=150,
                        null=True,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "good_habit",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="привычка, которую можно привязать к выполнению полезной привычки.",
                        null=True,
                        verbose_name="Признак полезной привычки",
                    ),
                ),
                (
                    "reword",
                    models.CharField(
                        blank=True,
                        help_text="чем пользователь должен себя вознаградить после выполнения",
                        max_length=50,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "periodicity",
                    models.IntegerField(
                        default=1,
                        help_text="Укажите кол-во дней, за которые необходимо выполнить привычку (по умолчанию раз в день)",
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "time_for_action",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="время, которое предположительно потратит пользователь на выполнение привычки",
                        null=True,
                        verbose_name="Время на действие",
                    ),
                ),
                (
                    "public_habits",
                    models.BooleanField(
                        blank=True,
                        default=True,
                        null=True,
                        verbose_name="Признак публичности",
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
