# Generated by Django 5.1.4 on 2025-01-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="action",
            field=models.CharField(
                help_text="Напиши что делаешь", max_length=150, verbose_name="Действие"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.IntegerField(
                blank=True,
                default=1,
                help_text="Укажите кол-во дней, за которые необходимо выполнить привычку (по умолчанию раз в день)",
                null=True,
                verbose_name="Периодичность",
            ),
        ),
    ]
